// ImageWalker by Zac Walker
//
// Purpose: ImageIndex: the index of every icon in the application bitmap.
//
// Copyright (C) 1998-2026 Zac Walker. MIT licence - see LICENSE.
// For more information on ImageWalker see www.ImageWalker.com

#pragma once


struct ImageIndex
{
	enum
	{
		None = -1,

		About = 96,
		ActualSize = 1,
		Add = 107,
		ArrangeIconsModified = 5,
		ArrangeIconsName = 2,
		ArrangeIconsSize = 3,
		ArrangeIconsType = 4,
		Back = 6,
		Close = 116,
		Copy = 7,
		CopyImage = 102,
		CopyTo = 8,
		CopyToNewLocation = 9,
		Cut = 10,
		Delete = 11,
		Description = 12,
		Down = 15,
		Download = 16,
		EditDescription = 14,
		Error = 69,
		Filter = 18,
		FilterColor = 91,
		FilterCrop = 88,
		FilterFrame = 89,
		FilterMultiple = 19,
		FilterRedEye = 90,
		FilterRotate = 85,
		FilterRotateLeft = 83,
		FilterRotateRight = 84,
		FilterText = 82,
		Fit = 20,
		Folders = 21,
		FullScreen = 22,
		GoTo = 23,
		GotoNewLocation = 24,
		Help = 25,
		Home = 104,
		ImageBack = 26,
		ImageNext = 27,
		Landscape = 70,
		Loader = 74,
		MoveTo = 28,
		MoveToNewlocation = 29,
		NewFolder = 30,
		Next = 31,
		Normal = 32,
		OK = 33,
		Open = 105,
		OpenContaining = 109,
		Options = 34,
		PageSetup = 35,
		Pan = 36,
		Parent = 37,
		Paste = 38,
		Playlist = 108,
		Previous = 92,
		Print = 99,
		PrintOptions = 100,
		PrintPreview = 101,
		Properties = 39,
		Property = 68,
		Refresh = 40,
		Remove = 41,
		Rename = 42,
		RotateFilesLeft = 86,
		RotateFilesRight = 87,
		Save = 43,
		SaveAs = 71,
		SaveContactSheet = 75,
		Search = 44,
		SearchAdvanced = 50,
		SearchFavorite = 47,
		SearchHere = 46,
		SearchMyPictures = 49,
		SearchRecent = 48,
		SearchStop = 45,
		ShowFullScreen = 51,
		Tag = 13,
		Task = 55,
		ThumbnailDetail = 58,
		ThumbnailMatrix = 59,
		ThumbnailNormal = 57,
		ThumbnailView = 56,
		ToolConvert = 77,
		ToolFilter = 81,
		ToolGif = 78,
		ToolJpeg = 76,
		ToolKeywords = 79,
		ToolRename = 80,
		Undo = 60,
		Up = 61,
	};
};
