#include "StdAfx.h"
#include "CommandBase.h"

CRect ImageWalkerCommandBarCtrl::m_rcButton;
LPCTSTR g_szToolBarItemTag = _T("Toolbar Buttons %d");
LPCTSTR g_szButtonItemTag = _T("Button %d");
LPCTSTR g_szSeparator = _T("Separator");

CommandInfo s_commands[] = { 
	{ ImageIndex::About,	ID_APP_ABOUT,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_APP_EXIT,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Back,	ID_BROWSE_BACK,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_DROPDOWN, -1 },
	{ ImageIndex::Next,	ID_BROWSE_FORWARD,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_DROPDOWN , -1 },
	{ ImageIndex::NewFolder,	ID_BROWSE_NEWFOLDER,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Parent,	ID_BROWSE_PARENT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Rename,	ID_BROWSE_RENAME,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::CaptureStop,	ID_CAPTURE_SREENCAPTURE_END,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Capture,	ID_CAPTURE_SREENCAPTUREENABLED,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::CopyToNewLocation,	ID_COPYTO_NEWLOCATION,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Copy,	ID_EDIT_COPY,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Cut,	ID_EDIT_CUT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Delete,	ID_EDIT_DELETE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ReallyDelete,	ID_EDIT_DELETE_PERM,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_EDIT_INVERTSELECTION,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Paste,	ID_EDIT_PASTE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Save,	ID_EDIT_SAVE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_EDIT_SAVE_MOVENEXT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },	
	{ ImageIndex::SaveAs,	ID_EDIT_SAVEAS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_EDIT_SELECT_ALL,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_EDIT_SELECTALLIMAGES,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Undo,	ID_EDIT_UNDO_IMAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_FILE_ACQUIRE_NATIVE,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_FILE_ACQUIRE,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::CopyTo,	ID_FILE_COPYTO,	CUpdateUIBase::UPDUI_MENUBAR | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_WHOLEDROPDOWN , -1 },
	{ ImageIndex::GoTo,	ID_FILE_GOTO,	CUpdateUIBase::UPDUI_MENUBAR | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_WHOLEDROPDOWN , -1 },
	{ ImageIndex::MoveTo,	ID_FILE_MOVETO,	CUpdateUIBase::UPDUI_MENUBAR | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_WHOLEDROPDOWN , -1 },
	{ ImageIndex::CopyTo,	ID_FILE_COPYTO_POPUP,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::MoveTo,	ID_FILE_MOVETO_POPUP,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Open,	ID_FILE_OPEN,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_FILE_OPEN_WITH,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::OpenContaining,	ID_FILE_OPENCONTAINING,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::PageSetup,	ID_FILE_PAGE_SETUP,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::PrintOptions,	ID_FILE_PRINT_OPTIONS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , ID_FILE_PRINT_OPTIONS },
	{ ImageIndex::Print,	ID_FILE_PRINT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , IDS_PRINT },
	{ ImageIndex::PrintPreview,	ID_VIEW_PRINT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , IDS_PRINT },
	{ ImageIndex::Properties,	ID_FILE_PROPERTIES,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_FILE_SELECTSOURCE,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_FILTER,	CUpdateUIBase::UPDUI_MENUBAR,	true,	BTNS_WHOLEDROPDOWN , -1 },
	{ ImageIndex::None,	ID_GOTO_ADDCURRENT,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::GotoNewLocation,	ID_GOTO_NEWLOCATION,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Help,	ID_HELP_FINDER,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Home,	ID_HELP_IMAGEWALKERHOMEPAGE,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Register,	ID_HELP_REGISTER,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::CopyImage,	ID_IMAGE_COPY,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Email,	ID_IMAGE_EMAIL,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::EditDescription,	ID_IMAGE_EDITDESCRIPTION, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Zip,	ID_FILE_ZIP,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::Wallpaper,	ID_IMAGE_SETASWAL,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Unload,	ID_IMAGE_UNLOAD,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_MOVECOPY_CLEARLOCATIONS,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::MoveToNewlocation,	ID_MOVETO_NEWLOCATION,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },	
	{ ImageIndex::SaveContactSheet,	ID_FILE_PRINTING_SAVECONTACTSHEET,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , ID_FILE_PRINTING_SAVECONTACTSHEET },
	{ ImageIndex::Up,	ID_PP_BACK,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::Down,	ID_PP_FORWARD,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::Fit,	ID_SCALE_FIT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SCALE_FILL,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::ActualSize,	ID_SCALE_100,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_DELAYBETWEENIMAGES_10SECONDS,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_DELAYBETWEENIMAGES_1SECOND,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_DELAYBETWEENIMAGES_2SECOND,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_DELAYBETWEENIMAGES_30SECONDS,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_DELAYBETWEENIMAGES_5SECONDS,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_EFFECTS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_TOOLBAR,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::ImageNext,	ID_SLIDESHOW_NEXTIMAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_NODELAY,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::SlideShowPlay,	ID_SLIDESHOW_PLAY,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::SlideShowStop,	ID_SLIDESHOW_STOP,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::SlideShowPause,	ID_SLIDESHOW_PAUSE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ImageBack,	ID_SLIDESHOW_PREVIOUSIMAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_RECURSSUBFOLDERS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_REPEAT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_SLIDESHOW_SHUFFLE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::Options,	ID_TOOLS_OPTIONS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_VIEW_CUSTOMIZEMAINTOOLBAR,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::FullScreen,	ID_VIEW_FULLSCREEN,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Refresh,	ID_VIEW_REFRESHX,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Normal,	ID_VIEW_NORMAL,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , IDS_VIEW },
	{ ImageIndex::None,	ID_VIEW_PINIMAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::PauseThumbnailing,	ID_VIEW_PAUSETHUMBNAILING,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_VIEW_STATUS_BAR,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::Web,	ID_VIEW_WEB,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , IDS_WEB },

	{ ImageIndex::ArrangeIconsName,	ID_ARRANGEICONS_NAME,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ArrangeIconsSize,	ID_ARRANGEICONS_SIZE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ArrangeIconsType,	ID_ARRANGEICONS_TYPE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ArrangeIconsModified,	ID_ARRANGEICONS_MODIFIED,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ArrangeIconsModified,	ID_ARRANGEICONS_DATETAKEN,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_ARRANGEICONS_MORE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	{ ImageIndex::SlideShow,	ID_VIEW_IMAGEFULLSCREEN,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::ArrangeIconsName,	ID_VIEW_ARRANGEICONS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, BTNS_WHOLEDROPDOWN, -1 },
	{ ImageIndex::ThumbnailView, ID_THUMBNAILS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	BTNS_WHOLEDROPDOWN , -1 },

	{ ImageIndex::ThumbnailNormal, ID_THUMBNAILS_THUMBNAIL,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::ThumbnailDetail,ID_THUMBNAILS_DETAIL,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },
	{ ImageIndex::ThumbnailMatrix, ID_THUMBNAILS_MATRIX,	CUpdateUIBase::UPDUI_MENUPOPUP,	false,	0 , -1 },

	{ ImageIndex::Folders,	ID_VIEW_FOLDERS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , IDS_FOLDERS },
	{ ImageIndex::Description,	ID_VIEW_DESCRIPTION, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::None,	ID_VIEW_ADVANCEDIMAGE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Address,	ID_VIEW_ADDRESS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	//{ ImageIndex::Search,	ID_VIEW_SEARCH, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	{ ImageIndex::None,	ID_OPTIONS_SHOWDESCRIPTIONSINDETAIL, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_OPTIONS_SHOWHIDDENFILES, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_OPTIONS_SHOWMETADATAMARKERS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_OPTIONS_SHOWTHUMBNAILTOOLTIPS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_OPTIONS_USESHORTDATES, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },
	{ ImageIndex::None,	ID_OPTIONS_ZOOMTHUMBNAILSINMATRIXVIEW, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , -1 },

	{ ImageIndex::SearchAdvanced,	ID_VIEW_SEARCHADVANCED,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	// Tools
	{ ImageIndex::ToolConvert,	ID_TOOLS_CONVERTIMAGES,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ToolFilter,	ID_TOOLS_BATCHPROCESS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ToolJpeg,	ID_TOOLS_LOSSLESS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::ToolKeywords,	ID_TOOLS_TAG,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	// Web
	{ ImageIndex::WebGenerate,	ID_FILE_WEBPAGE_GENERATEHTML,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , ID_FILE_WEBPAGE_GENERATEHTML },
	{ ImageIndex::WebBack,	ID_FILE_WEBPAGE_PREVIOUSWEBPAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::WebNext,	ID_FILE_WEBPAGE_NEXTWEBPAGE,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::Refresh,	ID_FILE_WEBPAGE_REFRESH,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , ID_FILE_WEBPAGE_REFRESH },
	{ ImageIndex::WebStop,	ID_FILE_WEBPAGE_STOP,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , ID_FILE_WEBPAGE_STOP },
	{ ImageIndex::OK,	ID_OK, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	false,	0 , ID_OK },
	{ ImageIndex::WebOptions,	ID_FILE_WEBPAGE_OPTIONS,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , ID_FILE_WEBPAGE_OPTIONS },

	// Search
	{ ImageIndex::SearchHere, ID_SEARCH_CURRENT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::SearchMyPictures, ID_SEARCH_MYPICTURES,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::SearchStop,	ID_SEARCH_STOP,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	{ ImageIndex::None,	ID_SEARCH_DATE,	CUpdateUIBase::UPDUI_MENUPOPUP,	true,	0 , -1 },
	{ ImageIndex::None,	ID_SEARCH_TEXT,	CUpdateUIBase::UPDUI_MENUPOPUP,	true,	0 , -1 },
	{ ImageIndex::None,	ID_TAG_AUTOSELECT,	CUpdateUIBase::UPDUI_MENUPOPUP,	true,	0 , -1 },
	{ ImageIndex::RotateFilesLeft,	ID_EDIT_ROTATELEFT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },
	{ ImageIndex::RotateFilesRight,	ID_EDIT_ROTATERIGHT,	CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR,	true,	0 , -1 },

	{ ImageIndex::None,	ID_TAG_REMOVE,	CUpdateUIBase::UPDUI_MENUPOPUP,	true,	0 , -1 },
	{ ImageIndex::None,	ID_FILE_ADDCOPYRIGHT,	CUpdateUIBase::UPDUI_MENUPOPUP,	true,	0 , -1 },

	{ ImageIndex::None, ID_FILTER_BLUR, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterColor, ID_FILTER_COLORADJUST, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_CONTRASTSTRETCH, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterCrop, ID_FILTER_CROP, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_DITHER, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_EDGE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_EMBOS, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_FRAME, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_GRAYSCALE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_NEGATE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_QUANTIZE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterRedEye, ID_FILTER_REDEYEREDUCTION, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_RESIZE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterRotate, ID_FILTER_ROTATE, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterRotateLeft, ID_FILTER_ROTATELEFT, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::FilterRotateRight , ID_FILTER_ROTATERIGHT, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_SHARPEN, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },
	{ ImageIndex::None, ID_FILTER_SOFTEN, CUpdateUIBase::UPDUI_MENUPOPUP | CUpdateUIBase::UPDUI_TOOLBAR, true, 0, -1 },

	{ ImageIndex::None,	-1,	0,	0, 0, 0 } };



int s_toolbarMain[] = { 
	ID_VIEW_FOLDERS,
	ID_VIEW_WEB,
	ID_VIEW_PRINT,
	0,	
	ID_BROWSE_BACK,
	ID_BROWSE_FORWARD,	
	ID_BROWSE_PARENT,
	0,	
	ID_VIEW_DESCRIPTION,
	0,
	ID_EDIT_UNDO_IMAGE,
	ID_EDIT_SAVE,
	0,
	ID_SLIDESHOW_PREVIOUSIMAGE,
	ID_SLIDESHOW_PLAY,
	ID_SLIDESHOW_NEXTIMAGE,
	0,
	ID_EDIT_DELETE,	
	ID_VIEW_REFRESHX,
	ID_VIEW_SEARCHADVANCED,
	ID_THUMBNAILS, 
	ID_VIEW_ARRANGEICONS, 
	0,	
	ID_FILE_GOTO,
	ID_FILE_COPYTO,
	ID_FILE_MOVETO,
	0,
	ID_HELP_FINDER,
	-1 };

int s_toolbarWeb[] = {
		ID_VIEW_FOLDERS,
		ID_VIEW_NORMAL,
		ID_VIEW_PRINT,
		0,
		ID_FILE_WEBPAGE_GENERATEHTML,
		ID_FILE_WEBPAGE_OPTIONS,
		0,
		ID_FILE_WEBPAGE_PREVIOUSWEBPAGE,
		ID_FILE_WEBPAGE_NEXTWEBPAGE,
		0,
		ID_FILE_WEBPAGE_REFRESH,
		ID_FILE_WEBPAGE_STOP,	
		0,
		ID_HELP_FINDER,
		-1 };

int s_toolbarPrint[] = {
	ID_VIEW_FOLDERS,
	ID_VIEW_NORMAL,
	ID_VIEW_WEB,
	0,
	ID_FILE_PRINT,
	ID_FILE_PAGE_SETUP,
	ID_FILE_PRINT_OPTIONS,
	0,
	ID_PP_BACK,
	ID_PP_FORWARD,
	0,	
	ID_FILE_PRINTING_SAVECONTACTSHEET,
	0,
	ID_HELP_FINDER,
	-1 }; 

