//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageWalker.rc
//
#define IDS_XMLIMPORT_TITLE             2
#define ID_SEARCHMYPICS                 3
#define IDC_OPEN                        3
#define IDC_NEXT                        3
#define IDS_XMLIMPORT_SUBTITLE          3
#define IDC_PREVIOUS                    4
#define IDS_XMLIMPORT_DESCRIPTION       4
#define IDS_XMLIMPORT_ABOUTTO           5
#define IDS_XMLIMPORT_COMPLETE          6
#define IDS_OUT_OF_MEMORY               7
#define IDS_PARSE_ERROR                 8
#define IDS_FAILED_OPEN_IMAGE           9
#define IDS_FAILED_SAVE_IMAGE           10
#define IDS_SECTION                     13
#define IDS_FAILED_OPEN                 14
#define IDR_MAINFRAME                   100
#define IDR_SUNFLOWER                   101
#define IDR_IMAGEWALKERSVR              102
#define IDS_TRANSLATE                   103
#define IDR_IMAGEWALKER                 104
#define IDR_MAINTESTDRIVER              105
#define IDR_POPUP_SLIDESHOW             106
#define IDR_PLUGPROTOCOL                107
#define IDR_POPUP_TOOLBAR               108
#define IDS_ACTIVEWINDOW                109
#define IDS_ADDRESS                     110
#define IDS_AGSS_SUBTITLE               111
#define IDS_AGSS_TITLE                  112
#define IDS_AREAAROUNDCUR               113
#define IDS_AT_LEAST                    114
#define IDS_AT_MOST                     115
#define IDS_AWCLIENT                    116
#define IDS_BROWSE_BACK                 117
#define IDS_BROWSE_FORWARD              118
#define IDS_BROWSE_PARENT               119
#define IDS_BUILDING_FILE_LIST          120
#define IDS_CANCELED                    121
#define IDS_FAILEDTO_CREATE_FILE        122
#define IDS_CATEGORY                    123
#define IDS_FAILEDTO_CREATE_FOLDER      124
#define IDS_COPYRIGHT                   125
#define IDS_FAILEDTO_CREATE_IMAGE       126
#define IDS_AUTHOR                      127
#define IDS_FAILEDTOOPENSTORAGE         128
#define IDS_QIFAILEDFORIPROPERTYSETSTORAGE 129
#define IDD_BUG_REPORT                  129
#define IDS_NOSUMMARYINFO               130
#define IDC_HEADING_TEXT                130
#define IDS_FILTERFACTORY               131
#define IDS_FAILEDTO_RENAME             132
#define IDS_FAILEDTO_SAVE               133
#define IDX_IW_CACHE                    134
#define IDS_FAILEDTO_SAVE_INDEX         134
#define IDS_FILTERFACTORY_DESC          135
#define IDS_FAILEDTO_SET_DESC           136
#define IDS_FAILEDTO_UPDATE             137
#define IDS_FAILEDTOCREATECOMBO         138
#define IDS_FAILEDTO_ZIP                139
#define IDS_ZIPPED                      140
#define IDS_FAILEDTOCREATEFPC           141
#define IDS_FAILEDTOCREATEFSC           142
#define IDS_FAILEDTOCREATEFTV           143
#define IDS_FAILEDTOCREATEFV            144
#define IDS_FAILEDTOLOADLIB             145
#define IDS_NOENTRYPOINT                146
#define IDS_FAILEDTOCREATEIVC           147
#define IDS_FAILEDTOCREATESSC           148
#define IDS_FAILEDTOCREATETOOLBAR       149
#define IDS_FAILEDTOCREATEWEBC          150
#define IDS_FAILEDTOLOADTWAIN           151
#define IDS_FAILEDTOOPENSSC             152
#define IDS_FAILEDTOREGISTERCOMMONCONTROLS 153
#define IDR_BLANK                       154
#define IDS_FAILEDTOSTART_ATL           154
#define IDS_FAILEDTOSTART_OLE           155
#define IDS_CLOSE                       156
#define IDS_CONVERT_BMP                 157
#define IDS_CONVERT_GIF                 158
#define IDC_HANDLINK                    158
#define IDS_CONVERT_JPEG                159
#define IDS_CONVERT_PNG                 160
#define IDS_CONVERT_TIFF                161
#define IDS_FAILEDTOCOPYORMOVE          162
#define IDS_FAILEDTOSAVEIMAGE           163
#define IDS_PRINTING                    164
#define IDS_COUND_NOT_DELETE            165
#define IDS_CS_SUBTITLE                 166
#define IDS_CS_TITLE                    167
#define IDS_DESKTOP                     168
#define IDS_DOESNOT_SUPPORT_METADATA    169
#define IDS_ED_SUBTITLE                 170
#define IDS_ED_TITLE                    171
#define IDS_EDIT_DELETE                 172
#define IDS_EMPTYFOLDER                 173
#define IDS_FAILEDTOSTARTCAP            174
#define IDS_FAVORITES                   175
#define IDS_FILE_HAS_NO_MATCH           176
#define IDS_FILES_CREATED               177
#define IDR_CREATE_SQL                  177
#define IDS_FILES_MODIFIED              178
#define IDR_POPUPS                      178
#define IDS_FOLDER_SKIPPED              179
#define IDR_POPUP_FOLDER                179
#define IDS_FONT                        180
#define IDD_DESCRIPTION_MAIN            180
#define IDS_GOTO_ADDCURRENT             181
#define IDC_COLORSELECT                 181
#define IDS_GOTO_NEWLOCATION            182
#define IDC_HANDDOWN                    182
#define IDS_HIDDEN                      183
#define IDC_HANDUP                      183
#define IDS_HOME                        184
#define IDD_TEST                        184
#define IDS_ID_SUBTITLE                 185
#define IDD_FLICKRUPLOAD                185
#define IDS_FRAME_NO                    186
#define IDS_ID_TITLE                    187
#define IDB_CAPTION_BUTTONS             187
#define IDS_FRAME_SOLID                 188
#define IDB_CAPTION_BUTTONS_HOVER       188
#define IDS_INVALID_CACHE_FILE_SAVE     189
#define IDB_SKIN_CAPTION                189
#define IDS_INVALID_CACHE_FILE_WITH_OS  190
#define IDS_INVALID_FILE                191
#define IDD_FLICKR_CREATESET            191
#define IDS_INVALID_INPUT               192
#define IDD_PROGRESS_ADVANCED           192
#define IDS_FRAME_BUTTON                193
#define IDD_DESCRIPTION                 193
#define IDS_INVALIDRINGCOUNT            194
#define IDC_INSERT                      194
#define IDS_INVALIDRINGLESSTHANONE      195
#define IDD_YESNO                       195
#define IDS_INVALIDRINGNUMBER           196
#define IDS_INVALIDSAVEFORMAT           197
#define IDS_IS_SUBTITLE                 198
#define IDB_FOLDEROPTIONS               198
#define IDS_IS_TITLE                    199
#define IDS_LAST_ACCESSED               200
#define IDS_LINKS                       201
#define IDS_MAPISENDFAIL                202
#define IDS_MOVECOPY_CLEARLOCATIONS     203
#define IDS_MOVETO_NEWLOCATION          204
#define IDS_MUST_SEL_TEMPLATE           205
#define IDS_FRAME_PRESSED               206
#define IDS_NO_IMAGES_TO_PRINT          207
#define IDS_NO_MATCH                    208
#define IDS_NOMAPI                      209
#define IDS_NOMEDIACONTROL              210
#define IDS_PRINT                       211
#define IDS_PRINTFAILED                 212
#define IDS_RAW_TITLE                   213
#define IDS_REFRESH                     214
#define IDS_SAVE_CHANGES                215
#define IDS_VIEW                        216
#define IDS_SAVECACHE                   217
#define IDS_SAVING_CACHE                218
#define IDS_SEARCH                      219
#define IDS_SLIDESHOW_NEXTIMAGE         220
#define IDS_SLIDESHOW_PLAY              221
#define IDS_SLIDESHOW_PREVIOUSIMAGE     222
#define IDS_SUBTITLE_CONV               223
#define IDS_TITLE_CONV                  224
#define IDS_TWAIN_ERROR                 225
#define IDS_UNDERCUR                    226
#define IDS_UNSUPPORTED_IMAGE_TYPE      227
#define IDS_VIEW_OPTIONS                228
#define IDS_WP_SUBTITLE                 229
#define IDS_WP_TITLE                    230
#define IDS_FILENAME                    231
#define IDS_FILETYPE                    232
#define IDS_FILESIZE                    233
#define IDS_FILEMODIFIED                234
#define IDS_FILECREATED                 235
#define IDS_FILEPATH                    236
#define IDS_UNKNOWNFILENAME             237
#define IDS_UNKNOWNTYPE                 238
#define IDS_UNKNOWNFILEPATH             239
#define IDS_NONE                        240
#define IDS_IPTC_RECORDVERSION          241
#define IDS_IPTC_OBJECTNAME             242
#define IDS_IPTC_EDITSTATUS             243
#define IDS_IPTC_EDITORIALUPDATE        244
#define IDS_IPTC_URGENCY                245
#define IDS_IPTC_SUBJECTREFERENCE       246
#define IDS_IPTC_CATEGORY               247
#define IDS_IPTC_SUPPLEMENTALCATEGORY   248
#define IDS_IPTC_FIXTUREIDENTIFIER      249
#define IDS_IPTC_KEYWORDS               250
#define IDS_IPTC_CONTENTLOCATIONCODE    251
#define IDS_IPTC_CONTENTLOCATIONNAME    252
#define IDS_IPTC_RELEASEDATE            253
#define IDS_IPTC_RELEASETIME            254
#define IDS_IPTC_EXPIRATIONDATE         255
#define IDS_IPTC_EXPIRATIONTIME         256
#define IDS_IPTC_SPECIALINSTRUCTIONS    257
#define IDS_IPTC_ACTIONADVISED          258
#define IDS_IPTC_REFERENCESERVICE       259
#define IDS_IPTC_REFERENCEDATE          260
#define IDS_IPTC_REFERENCENUMBER        261
#define IDS_IPTC_DATECREATED            262
#define IDS_IPTC_TIMECREATED            263
#define IDS_IPTC_DIGITALCREATIONDATE    264
#define IDS_IPTC_DIGITALCREATIONTIME    265
#define IDS_IPTC_ORIGINATINGPROGRAM     266
#define IDS_IPTC_PROGRAMVERSION         267
#define IDS_IPTC_OBJECTCYCLE            268
#define IDS_IPTC_BYLINE                 269
#define IDS_FRAME_PHOTO                 270
#define IDS_IPTC_CITY                   271
#define IDS_IPTC_SUBLOCATION            272
#define IDS_IPTC_PROVINCESTATE          273
#define IDS_ALT_PLUS                    274
#define IDS_CTRL_PLUS                   275
#define IDS_SHIFT_PLUS                  276
#define IDS_IPTC_HEADLINE               277
#define IDS_IPTC_CREDIT                 278
#define IDS_IPTC_SOURCE                 279
#define IDS_IPTC_COPYRIGHTNOTICE        280
#define IDS_IPTC_CONTACT                281
#define IDS_IPTC_CAPTIONABSTRACT        282
#define IDS_IPTC_WRITEREDITOR           283
#define IDS_IPTC_RASTERIZEDCAPTION      284
#define IDS_IPTC_IMAGETYPE              285
#define IDS_IPTC_IMAGEORIENTATION       286
#define IDS_IPTC_LANGUAGEIDENTIFIER     287
#define IDS_AND                         288
#define IDS_OR                          289
#define IDS_NOT                         290
#define IDS_BITMAPRESOURCENOTFOUND      291
#define IDS_FAILEDTOLOADBITMAPRESOURCE  292
#define IDS_YEAR                        293
#define IDS_MONTH                       294
#define IDS_DAYOFWEEK                   295
#define IDS_DAY                         296
#define IDS_HOUR                        297
#define IDS_MINUTE                      298
#define IDS_SECOND                      299
#define IDS_COMMAND                     300
#define IDS_TYPE                        301
#define IDS_NAME                        302
#define IDS_SHADOW                      303
#define IDS_FRAME                       304
#define IDS_IPTC_BYLINETITLE            305
#define IDS_IPTC_COUNTRYPRIMARYLOCATIONCODE 306
#define IDS_IPTC_COUNTRYPRIMARYLOCATIONNAME 307
#define IDS_IPTC_ORIGINALTRANSMISSIONREFERENCE 308
#define IDS_START_EVAL                  309
#define IDS_0DELAY                      310
#define IDS_FOLDER                      311
#define IDR_EXTRA                       312
#define IDS_FMT_LOADING                 312
#define IDD_HTML_OUTPUT_ADV             313
#define IDS_FMT_VIEWING                 313
#define IDS_FMT_EDITING                 314
#define IDS_DOWN                        315
#define IDS_UP                          316
#define IDS_FIT                         317
#define IDS_NOLOSS                      318
#define IDS_BUFFERING                   319
#define IDS_NOIMAGELOADED               320
#define IDS_IMAGEFILE                   321
#define IDS_TT_KB                       322
#define IDS_TT_SIZE                     323
#define IDS_TT_MODIFIED                 324
#define IDS_TT_TYPE                     325
#define IDS_NEW_IMAGE_NUM               326
#define IDS_NEW_IMAGE                   327
#define IDS_NEW_FOLDER_NUM              328
#define IDS_NEW_FOLDER                  329
#define IDS_IMAGES_FILES_FOLDERS        330
#define IDS_MOVING_FILE                 331
#define IDS_HAS_BEEN_UPDATED            332
#define IDS_HTML_PAGENOTFOUND           333
#define IDS_HTML_DEFAULT_FOOTER         334
#define IDS_HTML_DEFAULT_HEADER         335
#define IDS_ALL_FILES                   336
#define IDS_SETTING_FILES               337
#define IDS_HTML_DEFAULT_HOMELINK       338
#define IDS_MY_CAPTION                  339
#define IDS_HOT_KEY                     340
#define IDS_MODES                       341
#define IDS_LOCATIONS                   342
#define IDS_TITLE                       343
#define IDS_FILE                        344
#define IDS_COLOR_ADJUST                345
#define IDS_RED_EYE_REDUCTION           346
#define IDS_COLOR                       347
#define IDS_HISTOGRAM_EQUALIZATION      348
#define IDS_CONTRAST_STRETCH            349
#define IDS_DITHER                      350
#define IDS_DITHER_DESC                 351
#define IDS_QUANTIZE                    352
#define IDS_QUANTIZE_DESC               353
#define IDS_FILTER                      354
#define IDS_CROP                        355
#define IDS_TIP1                        356
#define IDS_RESIZE                      357
#define IDS_GREYSCALE                   358
#define IDS_EMBOS                       359
#define IDS_BLUR                        360
#define IDS_SOFTEN                      361
#define IDS_SHARPEN                     362
#define IDS_EDGE                        363
#define IDS_TEXT                        364
#define IDS_TEXT_CAPTION                365
#define IDS_ROTATE                      366
#define IDS_ROTATE_DESC                 367
#define IDS_ANYMONTH                    368
#define IDS_JANUARY                     369
#define IDS_PIXELS_PER_INCH             370
#define IDS_PIXELS_PER_CM               371
#define IDS_FEBRUARY                    372
#define IDS_MARCH                       373
#define IDS_APRIL                       374
#define IDS_MAY                         375
#define IDS_JUNE                        376
#define IDS_JULY                        377
#define IDS_AUGUST                      378
#define IDS_SEPTEMBER                   379
#define IDS_PIXELS                      380
#define IDS_INCHES                      381
#define IDS_CENTIMETERS                 382
#define IDS_LOSSLESSJPEG                383
#define IDS_BATCHPROCESS                384
#define IDS_LOSSLESSJPEG_DESC           385
#define IDS_FILTERIMAGES                386
#define IDS_FILTERIMAGES_DESC           387
#define IDS_RENAMEFILESERIES            388
#define IDS_RENAMEFILESERIES_DESC       389
#define IDS_CONVERTIMAGES               390
#define IDS_CONVERTIMAGES_DESC          391
#define IDS_ADDKEYWORDS                 392
#define IDS_ADDKEYWORDS_DESC            393
#define IDS_CREATEGIFSLIDESHOW          394
#define IDS_PUBLISHIMAGES               395
#define IDS_CREATEGIFSLIDESHOW_DESC     396
#define IDS_JPEG_TITLE                  397
#define IDS_JPEG_DESC                   398
#define IDS_J2K_TITLE                   399
#define IDS_J2K_DESC                    400
#define IDS_BMP_TITLE                   401
#define IDS_BMP_DESC                    402
#define IDS_GIF_TITLE                   403
#define IDS_GIF_DESC                    404
#define IDS_PNG_TITLE                   405
#define IDS_PNG_DESC                    406
#define IDS_TIFF_TITLE                  407
#define IDS_TIFF_DESC                   408
#define IDS_WMF_TITLE                   409
#define IDS_WMF_DESC                    410
#define IDS_CDF_TITLE                   411
#define IDS_CDF_DESC                    412
#define IDS_MISC_TITLE                  413
#define IDS_MISC_DESC                   414
#define IDS_HISTOGRAM_EQUALIZATION_DESC 415
#define IDS_CONTRAST_STRETCH_DESC       416
#define IDS_RED_EYE_REDUCTION_DESC      417
#define IDS_COLOR_ADJUST_DESC           418
#define IDS_CROP_DESC                   419
#define IDS_OCTOBER                     420
#define IDS_RESIZE_DESC                 421
#define IDS_GREYSCALE_DESC              422
#define IDS_EMBOS_DESC                  423
#define IDS_BLUR_DESC                   424
#define IDS_SOFTEN_DESC                 425
#define IDS_SHARPEN_DESC                426
#define IDS_EDGE_DESC                   427
#define IDS_SHADOW_DESC                 428
#define IDS_FRAME_DESC                  429
#define IDS_TEXT_CAPTION_DESC           430
#define IDS_DECODING_FMT                431
#define IDS_ENCODING_FMT                432
#define IDS_BMP_FMT                     433
#define IDS_ANIMATED                    434
#define IDS_INTERLACED                  435
#define IDS_READMULTIPLEFAILED          436
#define IDS_FAILEDTOLOCKBYTES           437
#define IDS_FAILEDTOMANAGEJP2STREAM     438
#define IDS_FAILEDTODECODEIMAGEFILE     439
#define IDS_FAILEDTOALLOCATEMEMORY      440
#define IDS_FAILEDTOCREATEIMAGE         441
#define IDS_FAILEDTOENCODE              442
#define IDS_FAILEDTOLOAD                443
#define IDS_INVALIDFILEHEADER           444
#define IDS_IMAGETOLARGE                445
#define IDS_JPEGTRANSFORM               446
#define IDS_EMF_FMT                     447
#define IDS_ALDUS_FMT                   448
#define IDS_PNG_INTERLACED_FMT          449
#define IDS_PNG_FMT                     450
#define IDS_TIFF_FMT                    451
#define IDS_FAILEDTOOPENFILEIN          452
#define IDS_FAILEDTOOPENFILEOUT         453
#define IDS_TOOL_CONV_TITLE             454
#define IDS_TOOL_CONV_SUBTITLE          455
#define IDS_TOOL_CONV_DESC              456
#define IDS_TOOL_CONV_ABOUTTO           457
#define IDS_TOOL_CONV_COMPLETED         458
#define IDS_FAILETOOPENFILE             459
#define IDS_SELECTED                    460
#define IDS_ALL                         461
#define IDS_FAILEDTORENAME              462
#define IDS_TOOL_RESIZE_TITLE           463
#define IDS_TOOL_RESIZE_SUBTITLE        464
#define IDS_TOOL_RESIZE_DESC            465
#define IDS_TOOL_RESIZE_ABOUTTO         466
#define IDS_TOOL_RESIZE_COMPLETED       467
#define IDS_TOOL_PROPERTY_TITLE         468
#define IDS_TOOL_PROPERTY_SUBTITLE      469
#define IDS_TOOL_PROPERTY_DESC          470
#define IDS_TOOL_PROPERTY_COMPLETED     471
#define IDS_TOOL_PROPERTY_ABOUTTO       472
#define IDS_TOOL_RENAME_TITLE           473
#define IDS_TOOL_RENAME_SUBTITLE        474
#define IDS_TOOL_RENAME_DESC            475
#define IDS_TOOL_RENAME_COMPLETED       476
#define IDS_TOOL_RENAME_ABOUTTO         477
#define IDS_TOOL_GIFSS_TITLE            478
#define IDS_TOOL_GIFSS_SUBTITLE         479
#define IDS_TOOL_GIFSS_DESC             480
#define IDS_TOOL_GIFSS_COMPLETED        481
#define IDS_TOOL_GIFSS_ABOUTTO          482
#define IDS_TOOL_JPEG_TITLE             483
#define IDS_TOOL_JPEG_SUBTITLE          484
#define IDS_TOOL_JPEG_DESC              485
#define IDS_TOOL_JPEG_ABOUTTO           486
#define IDS_TOOL_JPEG_COMPLETED         487
#define IDS_TOOL_GIFSS_SHOW             488
#define IDS_EXTENSION                   489
#define IDS_FOLDERS                     490
#define IDS_FAILEDTOSTART               491
#define IDS_REINSTALL                   492
#define IDS_REGCTRLENTRYPOINTFAILED     493
#define IDS_REGCTRLSUCCEEDED            494
#define IDS_TRYINGTOREGISER             495
#define IDS_SERIOUSERROR                496
#define IDS_READY                       497
#define IDS_IMAGEVIEW                   498
#define IDS_SAVINGIMAGEFILE             499
#define IDS_STATUS_REMAINING            500
#define IDS_STATUS_SECONDS              501
#define IDS_STATUS_NORMAL               502
#define IDS_STATUS_SEARCHING            503
#define IDS_STATUS_FOUND                504
#define IDS_STATUS_SEARCHINGFOLDER      505
#define IDS_OPENEDFOLDER                506
#define IDS_NODELAY                     507
#define IDS_SECONDS_FMT                 508
#define IDS_SCALE                       509
#define IDS_DELAY                       510
#define IDS_DOWNLOADING                 511
#define IDS_PRINT_HEADER                512
#define IDS_PRINT_FOOTER                513
#define IDS_PRINT_PAGE_FMT              514
#define IDS_PRINT_JOB_NAME              515
#define IDS_TOOL_CONTACTSHEET_ABOUTTO   516
#define IDS_TOOL_CONTACTSHEET_DEFAULTFILE 517
#define IDS_TOOL_CONTACTSHEET_TITLE     518
#define IDS_TOOL_CONTACTSHEET_SUBTITLE  519
#define IDS_TOOL_CONTACTSHEET_DESC      520
#define IDS_TOOL_CONTACTSHEET_COMPLETE  521
#define IDS_TOOL_WEB_ABOUTTO            522
#define IDS_TOOL_WEB_ABOUTTO2           523
#define IDS_TOOL_WEB_TITLE              524
#define IDS_TOOL_WEB_SUBTITLE           525
#define IDS_TOOL_WEB_DESC               526
#define IDS_TOOL_WEB_COMPLETE           527
#define IDS_TOOL_WEB_SHOW               528
#define IDS_FAILEDTOWRITEINDEXFILE      529
#define IDS_FAILEDTOWRITEHTML           530
#define IDS_FAILEDTOWRITEFILE           531
#define IDS_FAILEDTOWRITETHUMBNAIL      532
#define IDS_FAILEDTOWRITEINDEX          533
#define IDS_NOERRORS                    534
#define IDS_EXIT_WIZARD                 535
#define IDS_STATUS                      536
#define IDS_TWAIN_ERROR_FMT             537
#define IDS_TWAIN_ERROR_OPEN_DSM        538
#define IDS_TWAIN_ERROR_OPEN_SOURCE     539
#define IDS_TWAIN_ERROR_ENABLE_SOURCE   540
#define IDS_TWAIN_ERROR_NOT_4           541
#define IDS_TWAIN_ERROR_CAP_SET         542
#define IDS_CACHE_FILES                 543
#define IDS_RIGHTMOUSEBUTTONISDISABLED  544
#define IDS_TRUNCATEDFILE               545
#define IDS_PSD_TITLE                   546
#define IDS_PSD_DESC                    547
#define IDS_PSD_FMT                     548
#define IDS_FILEMODIFIED_TIME           549
#define IDS_FILECREATED_TIME            550
#define ID_COPYTO_PRE                   551
#define ID_MOVETO_PRE                   552
#define IDS_COPYTO_NEWLOCATION          553
#define IDS_DEPTH                       554
#define IDS_WIDTH                       555
#define IDS_HEIGHT                      556
#define IDS_FAILEDTO_SAVE_IMAGE_TYPE    557
#define IDS_FAILEDTOSENDEMAIL           558
#define IDS_PROCESSING_FOLDER_FMT       559
#define IDS_OPTION_FULLSCREEN           560
#define IDS_DOESNOT_SUPPORT_METADATA_SHORT 561
#define IDS_FILE_ERROR                  562
#define IDS_LOW_LEVEL_ERROR_FMT         563
#define IDR_POPUP_IMAGE                 564
#define IDS_OPTION_AUTOSAVE             565
#define IDS_OPTION_SHOWTOOLTIPS         566
#define IDS_OPTION_SHOWMARKERS          567
#define IDS_OPTION_SHOWHIDDENFILES      568
#define IDS_OPTION_SHORTDATES           569
#define IDS_OPTION_WALKFOLDERS          570
#define IDS_ZIP_FILES                   571
#define IDS_ZIPPNG                      572
#define IDS_EMAILING                    573
#define IDS_GIF_FILES                   574
#define IDS_READONLY                    575
#define IDS_OPTION_SYSTEMTHUMBS         576
#define IDS_NEGATE_DESC                 577
#define IDS_NEGATE                      578
#define IDS_ROTATE_LEFT                 579
#define IDS_ROTATE_RIGHT                580
#define IDS_ROTATE_LEFT_DESC            581
#define IDS_ROTATE_RIGHT_DESC           582
#define IDS_BATCHONEFORALL              583
#define IDS_TESTS                       584
#define IDS_TEST_FILTERS                585
#define IDS_TEST_FORMATS                586
#define IDS_TEST_HTML                   587
#define IDS_STARTED_AT                  588
#define IDS_MAIN_WINDOW_CREATED         589
#define IDS_TEST_PROPERTIES             590
#define IDS_TEST_LOSSLESS               591
#define IDS_TEST_CONTACTSHEET           592
#define IDS_METADATA_COMMON             593
#define IDS_METADATA_IPTC               594
#define IDS_METADATA_EXIF               595
#define IDS_METADATA_IMAGE              596
#define IDS_NOVEMBER                    597
#define IDS_DECEMBER                    598
#define IDS_CANGETHUMBSIZE              599
#define IDS_WPG_TITLE                   600
#define IDS_WPG_DESC                    601
#define IDS_RAW_DESC                    602
#define ID_GOTO_PRE                     603
#define IDS_UPLOADING                   604
#define IDS_MOVECOPY_NEWLOCATION        605
#define IDS_MEDIA_TITLE                 606
#define IDS_MEDIA_DESC                  607
#define IDS_OK                          608
#define IDS_HELP                        609
#define IDS_SVG_TITLE                   610
#define IDS_SVG_DESC                    611
#define IDS_TAG                         612
#define IDS_TAGGING                     613
#define IDS_FILL                        614
#define IDS_REMOVING_TAG                615
#define IDS_TIP2                        616
#define IDS_TIP3                        617
#define IDS_TIP4                        618
#define IDS_TIP5                        619
#define IDS_TIP6                        620
#define IDS_START_FREE                  621
#define IDS_START_REGISTERED            622
#define IDS_JBIG_TITLE                  623
#define IDS_JBIG_DESC                   624
#define IDS_XML_FILES                   625
#define IDS_WEB                         626
#define IDS_EXIFAUTOROTATE              627
#define IDS_QUERYUNDO                   628
#define IDS_SHOW_DESCRIPTIONS           629
#define IDS_ZOOM_THUMBNAILS             630
#define IDB_TB_IMAGEALPHA               700
#define IDB_TB_IMAGE                    701
#define IDS_NAME2                       1000
#define IDS_DESC                        1001
#define IDS_TYPE2                       1002
#define IDS_SIZE                        1003
#define IDS_CRASH_DUMP                  1004
#define IDS_CRASH_LOG                   1005
#define IDS_SYMBOL_FILE                 1006
#define IDC_PUBLIC                      1009
#define IDC_PRIVATE                     1010
#define IDC_FRIENDS                     1011
#define IDC_FAMILY                      1012
#define IDC_MOVE                        1031
#define IDC_SELECT                      1032
#define IDI_DEFAULT                     1033
#define IDC_ABOUT_TO_INFO               1034
#define IDI_FOLDER                      1034
#define IDC_ADD                         1035
#define IDI_IMAGEWALKER                 1035
#define IDC_ADVANCED                    1036
#define IDC_AND                         1037
#define IDC_ASPECT                      1038
#define IDC_ASSENDING                   1039
#define IDC_BLUE                        1041
#define IDC_BLUE_SLIDER                 1042
#define IDC_RESIZE_LENGTH               1042
#define IDC_BRIGHTNESS                  1043
#define IDC_BRIGHTNESS_SLIDER           1044
#define IDC_BROWSE                      1045
#define IDC_BYLINE                      1046
#define IDC_BYLINETITLE                 1047
#define IDC_CAPTION                     1048
#define IDC_CAPTION_WRITER              1049
#define IDC_CASE                        1050
#define IDC_CATEGORY                    1051
#define IDC_CITY                        1052
#define IDC_PHOTOSET                    1052
#define IDC_COMBOBOXEX                  1055
#define IDC_COMMAND                     1056
#define IDC_CONTRAST                    1057
#define IDC_CONTRAST_SLIDER             1058
#define IDC_COPYRIGHT                   1059
#define IDC_COUNTRY_NAME                1060
#define IDC_CREDIT                      1061
#define IDC_DATE_CREATED                1063
#define IDC_DEGREES                     1064
#define IDC_DELAY                       1065
#define IDC_DESCRIPTION                 1066
#define IDC_DROP_EDGE                   1071
#define IDC_EDIT                        1072
#define IDC_END_COMPLETED               1073
#define IDC_EXT                         1074
#define IDC_FILE                        1075
#define IDC_FILES_ALL                   1076
#define IDC_FILES_SELECTED              1077
#define IDC_FOLDER                      1078
#define IDC_FILES_PLAY_LIST             1078
#define IDC_FOOTER                      1079
#define IDC_CLEAR                       1080
#define IDC_FILENAME                    1081
#define IDC_COMPACT                     1082
#define IDC_LOSSLESS                    1084
#define IDC_FRAME1                      1085
#define ID_SEARCHCURRENT                1085
#define IDC_FRAME2                      1086
#define IDC_ACCOUNT                     1086
#define IDC_FRAME3                      1087
#define IDC_RESIZE                      1087
#define IDC_EXTENSION                   1088
#define IDC_IMAGEID                     1089
#define IDC_TAB1                        1090
#define IDC_GREEN                       1091
#define IDC_MESSAGE                     1091
#define IDC_GREEN_SLIDER                1092
#define IDC_GREYSCALE                   1093
#define IDC_NAME                        1094
#define IDC_HEADER                      1095
#define IDC_READONLY                    1095
#define IDC_HEADLINE                    1096
#define IDC_CROP_HELP                   1096
#define IDC_HEIGHT                      1097
#define IDC_HOME                        1098
#define IDC_BORDER                      1098
#define IDC_HOTKEY                      1099
#define IDC_HUE                         1100
#define IDC_HUE_SLIDER                  1101
#define IDC_INFO                        1102
#define IDC_INTRO_DESCRIPTION           1103
#define IDC_INTRO_SUBTITLE              1104
#define IDC_INTRO_TITLE                 1105
#define IDC_KEEP_ASPECT                 1106
#define IDC_TAGS                        1107
#define IDC_LIGHTNESS                   1109
#define IDC_LIGHTNESS_SLIDER            1110
#define IDC_LIST                        1111
#define IDC_LIST1                       1112
#define IDC_MIRROR_LR                   1114
#define IDC_MIRROR_TB                   1115
#define IDC_MODE                        1116
#define IDC_MOVE_DOWN                   1118
#define IDC_MOVE_UP                     1119
#define IDC_NONE                        1121
#define IDC_NOT                         1122
#define IDC_OBJECT_NAME                 1123
#define IDC_ONE_PER_PAGE                1124
#define IDC_OPTIMIZE                    1125
#define IDC_OPTIONS                     1126
#define IDC_OR                          1127
#define IDC_ORIGINAL_TR                 1128
#define IDC_OVERWRITE                   1129
#define IDC_FLICKRID                    1129
#define IDC_PREVIEW                     1130
#define IDC_PERCENT                     1131
#define IDC_PROGRESS                    1132
#define IDC_PROGRESS2                   1133
#define IDC_STATUS                      1134
#define IDC_STATUS2                     1135
#define IDC_PROGRESSIVE                 1136
#define IDC_PROPERTY                    1137
#define IDC_PROPS                       1138
#define IDC_PROPTITLE                   1139
#define IDC_PROVENCE_STATE              1140
#define IDC_QUALITY                     1141
#define IDC_QUALITY_SLIDER              1142
#define IDC_RECURSE                     1143
#define IDC_RED                         1144
#define IDC_RED_SLIDER                  1145
#define IDC_REG1                        1146
#define IDC_REG2                        1147
#define IDC_REG3                        1148
#define IDC_REG4                        1149
#define IDC_REGISTER                    1150
#define IDC_REMOVE                      1151
#define IDC_REMOVE_ILLEGAL              1152
#define IDC_DISABLE_RIGHTCLICK          1153
#define IDC_REPEAT                      1153
#define IDC_AUTORUN                     1154
#define IDC_REPORT                      1154
#define IDC_ROTATE_180                  1155
#define IDC_SHARPEN                     1155
#define IDC_ROTATE_270                  1156
#define IDC_ROTATE_90                   1157
#define IDC_ROTATE_BEST_FIT             1158
#define IDC_ROTATE_X                    1160
#define IDC_SATURATION                  1161
#define IDC_SATURATION_SLIDER           1162
#define IDC_SAVE_OPTIONS                1164
#define IDC_SCALE                       1165
#define IDC_SCALE_DOWN                  1166
#define IDC_SEARCH_DATE_MODIFIED        1167
#define IDC_SEARCH_DATE_TAKEN           1168
#define IDC_SEARCH_DATE_DAY_COUNT       1169
#define IDC_SEARCH_KB                   1178
#define IDC_SEARCH_ADV                  1180
#define IDC_SEARCH_TEXT                 1181
#define IDC_SEARCH_ONLYSHOWIMAGES       1183
#define IDC_SELECTED                    1189
#define IDC_SERACH_SIZE                 1190
#define IDC_SHOW_BUTTONS                1194
#define IDC_SHOW_FOOTERS                1195
#define IDC_SHOW_HEADERS                1197
#define IDC_SHOW_OUTPUT                 1198
#define IDC_SHOW_PAGENUMBERS            1199
#define IDC_SHOWPREVIEW                 1200
#define IDC_SHUFFLE                     1201
#define IDC_SIZE_KB                     1202
#define IDC_SIZE_TYPE                   1203
#define IDC_MONTH                       1204
#define IDC_SORT                        1205
#define IDC_YEAR                        1205
#define IDC_SOURCE                      1206
#define IDC_SPECIAL_INSTRUCTIONS        1207
#define IDC_START_AT                    1208
#define IDC_START_AT_PICK               1209
#define IDC_STYLE_SHEET                 1210
#define IDC_SUB_CATEGORY                1211
#define IDC_SUBFOLDER                   1212
#define IDC_TEMPLATE                    1213
#define IDC_TITLE                       1214
#define IDC_TODAY                       1215
#define IDC_WANT_CURSOR                 1217
#define IDC_WEB_PAGE                    1218
#define IDC_WIDTH                       1219
#define IDC_WRITE_FOLDER                1221
#define IDD_ABOUT                       1222
#define IDD_ACCELERATOR_EDIT            1223
#define IDD_ACCELERATOR_LIST            1224
#define IDD_ASSOCIATION                 1227
#define IDD_CAPTURE                     1228
#define IDD_COLOR_ADJUST                1229
#define IDD_CONVERT                     1232
#define IDD_CS_FORMAT                   1233
#define IDD_CS_OUTPUT                   1234
#define IDD_CS_SCALE                    1235
#define IDD_FILE_ABOUT_TO_PROCESS       1238
#define IDD_FILE_INPUT                  1239
#define IDD_FILE_OUTPUT                 1240
#define IDD_FILE_PROGRESS               1241
#define IDD_FILES_END                   1242
#define IDD_FILES_INTRO                 1243
#define IDD_IMAGEFILE                   1246
#define IDD_IMAGEFILE_SAVE              1247
#define IDD_JPEG                        1248
#define IDD_JPEG1                       1250
#define IDD_JPEG2                       1251
#define IDD_PROGRESS                    1256
#define IDD_PROPERTY_ADD                1257
#define IDD_PROPERTY_SORT               1258
#define IDD_REGISTRATION                1259
#define IDD_ROTATE                      1261
#define IDD_SCALE                       1263
#define IDD_SEARCH_ADVANCED             1265
#define IDD_SEARCH                      1266
#define IDD_SORT                        1268
#define IDD_VO_ANNOTATIONS              1269
#define IDD_VO_BEHAVIOUR                1270
#define IDD_VO_CAPTURE                  1271
#define IDD_VO_COLUMNS                  1272
#define IDD_VO_SLIDESHOW                1274
#define IDD_VO_THUMBNAILS               1276
#define IDD_WALLPAPER                   1277
#define IDD_HTML_OUTPUT                 1279
#define IDD_HTML_THUMBNAILS             1284
#define IDC_CY                          1294
#define IDC_PREVIEW_FRAME               1319
#define IDC_RESET                       1320
#define IDC_BESTQUAL                    1321
#define IDC_RESOLUTION                  1322
#define IDC_CX                          1323
#define IDC_TYPE                        1324
#define IDC_RES_LBL                     1325
#define IDC_IMAGES_ONLY                 1327
#define IDC_FILTER                      1327
#define IDC_BREADCRUMB                  1329
#define IDC_ZIP                         1333
#define IDC_SHRINK                      1334
#define ID_OK                           2004
#define ID_CANCEL                       2006
#define IDD_EMAIL                       2007
#define IDD_VO_CACHE                    2008
#define IDD_DESCRIPTION_EXIF            2010
#define IDD_CROP                        2011
#define IDD_HTML_TEMPLATE               2012
#define IDD_HTML_INDEX                  2013
#define IDD_PRINT_LAYOUT                2014
#define IDD_PRINT_HEADER                2015
#define IDD_FLICKRUPLOAD_MULTI          2016
#define IDD_ADDCOPYRIGHT                2017
#define IDD_FLICKR_DOWNLOADBYID         2019
#define IDD_HTML_ADVANCED               2020
#define IDD_DESCRIPTION_XMP             2022
#define IDD_RENAME_SINGLE               2023
#define IDD_DESCRIPTION_DETAILS         2024
#define IDD_DESCRIPTION_IPTC            2025
#define IDD_TAG                         2026
#define IDD_RENAME_SINGLE1              2027
#define IDD_RENAME                      2027
#define IDD_JPEG3                       2028
#define IDD_TOOL_RESIZE                 2028
#define ID_BROWSE_BACK                  40006
#define ID_BROWSE_FORWARD               40008
#define ID_BROWSE_NEWFOLDER             40010
#define ID_BROWSE_PARENT                40012
#define ID_BROWSE_RENAME                40013
#define ID_CAPTURE_SREENCAPTURE_END     40015
#define ID_CAPTURE_SREENCAPTUREENABLED  40016
#define ID_COLOR_BRIGHTNESS             40017
#define ID_CONTRAST_CONTRAST            40018
#define ID_COPYTO_NEWLOCATION           40019
#define ID_CREATE_WEB_PAGES             40020
#define ID_DEFORM_EXPLODE               40021
#define ID_DEFORM_FLIP                  40022
#define ID_DEFORM_MIRROR                40023
#define ID_DEFORM_ROTATE                40024
#define ID_DESCTIPTION_EXIF             40025
#define ID_DESCTIPTION_IPTC             40026
#define ID_DUMMY_MULTIPAGE              40027
#define ID_EDIT_BRIGHTNESS              40029
#define ID_EDIT_CONTRAST                40030
#define ID_EDIT_CROP                    40032
#define ID_EDIT_DELETE                  40033
#define ID_EDIT_GET                     40034
#define ID_EDIT_INVERTSELECTION         40035
#define ID_EDIT_NEW                     40036
#define ID_EDIT_POINTER                 40037
#define ID_EDIT_REDUCE                  40038
#define ID_EDIT_REVERTDESCRIPTION       40039
#define ID_EDIT_ROTATE                  40040
#define ID_EDIT_SAVE                    40041
#define ID_EDIT_SAVEAS                  40043
#define ID_EDIT_SCALE                   40045
#define ID_EDIT_SELECTALLIMAGES         40046
#define ID_EDIT_UNDO_IMAGE              40047
#define ID_EDIT_WORD_WRAP               40049
#define ID_FILE_ACQUIRE                 40050
#define ID_FILE_ACQUIRE_NATIVE          40051
#define ID_FILE_COPYTO                  40053
#define ID_FILE_GOTO                    40054
#define ID_FILE_MOVETO                  40055
#define ID_FILE_NEW_WINDOW              40056
#define ID_FILE_PRINTING_PRINTONEIMAGEPERPAGE 40057
#define ID_FILE_PRINTING_SAVECONTACTSHEET 40058
#define ID_FILE_PROPERTIES              40059
#define ID_FILE_SELECTSOURCE            40060
#define ID_FILE_WEBPAGE_GENERATEHTML    40061
#define ID_FILE_WEBPAGE_NEXTWEBPAGE     40062
#define ID_FILE_WEBPAGE_PREVIOUSWEBPAGE 40063
#define ID_FILE_WEBPAGE_REFRESHWEBPAGE  40064
#define ID_FILTER                       40065
#define ID_FILTER_APPLY                 40066
#define ID_FOLDER_DETAIL                40068
#define ID_FOLDER_NORMAL                40069
#define ID_FOLDER_PRINTVIEW             40070
#define ID_FOLDER_SORT                  40071
#define ID_FOLDER_VIEWOPTIONS           40072
#define ID_FOLDER_VIEWOPTIONS2          40073
#define ID_GOTO_ADDCURRENT              40074
#define ID_GOTO_NEWLOCATION             40075
#define ID_HELP_BUGREPORT               40077
#define ID_HELP_DIAGNOSTICS_DEPENDS     40078
#define ID_HELP_DIAGNOSTICS_REREGISTERCONTROLS 40079
#define ID_HELP_IMAGEWALKERHOMEPAGE     40080
#define ID_HELP_REGISTER                40081
#define ID_IMAGE_COPY                   40082
#define ID_IMAGE_EMAIL                  40083
#define ID_IMAGE_SCALE                  40084
#define ID_IMAGE_SETASWAL               40085
#define ID_IMAGE_UNLOAD                 40086
#define ID_MODE                         40087
#define ID_MODE_ACTUALSIZE              40094
#define ID_MODE_BLACKBACKGROUND         40096
#define ID_MODE_FITTOWINDOW             40097
#define ID_MODE_OPTIONS                 40098
#define ID_MODE_ROTATE                  40099
#define ID_MODE_SCALEDOWNTOFIT          40101
#define ID_MODE_SCALEUPTOFIT            40102
#define ID_MODE_SMOOTHSCALE             40103
#define ID_MOVECOPY_CLEARLOCATIONS      40105
#define ID_MOVECOPY_NEWLOCATION         40106
#define ID_MOVETO_NEWLOCATION           40107
#define ID_MULTIPAGE                    40108
#define ID_NAVIGATE                     40109
#define ID_OPTIONS_APPLY                40112
#define ID_OPTIONS_REVERT               40116
#define ID_PP_BACK                      40117
#define ID_PP_FORWARD                   40118
#define ID_REDUCECOLORS_BLUE            40119
#define ID_REDUCECOLORS_GREEN           40120
#define ID_REDUCECOLORS_RED             40121
#define ID_REDUCECOLORS_TO256           40122
#define ID_SCALE_100                    40124
#define ID_SCALE_200                    40125
#define ID_SCALE_50                     40126
#define ID_SCALE_DOWN                   40127
#define ID_SCALE_FIT                    40128
#define ID_SCALE_UP                     40129
#define ID_SELECT_BROWSE                40130
#define ID_SELECT_CIRCLE                40131
#define ID_SELECT_CURRENTFOLDER         40132
#define ID_SELECT_RECT                  40133
#define ID_SELECT_SOURCE                40134
#define ID_SLIDESHOW_DELAYBETWEENIMAGES_10SECONDS 40135
#define ID_SLIDESHOW_DELAYBETWEENIMAGES_1SECOND 40136
#define ID_SLIDESHOW_DELAYBETWEENIMAGES_30SECONDS 40137
#define ID_SLIDESHOW_DELAYBETWEENIMAGES_5SECONDS 40138
#define ID_SLIDESHOW_EFFECTS            40139
#define ID_SLIDESHOW_NEXTIMAGE          40142
#define ID_SLIDESHOW_NODELAY            40144
#define ID_SLIDESHOW_PLAY               40145
#define ID_SLIDESHOW_PAUSE              40146
#define ID_SLIDESHOW_PREVIOUSIMAGE      40147
#define ID_SLIDESHOW_PREVIOUSIMAGE2     40148
#define ID_SLIDESHOW_RECURSSUBFOLDERS   40149
#define ID_SLIDESHOW_REPEAT             40150
#define ID_SLIDESHOW_SHUFFLE            40152
#define ID_SLIDESHOW_STOP               40154
#define ID_TOOLS_EMAIL                  40155
#define ID_TOOLS_FILEASSOCIATION        40156
#define ID_TOOLS_OPTIONS                40157
#define ID_TOOLS_SETASWAL               40161
#define ID_TOOLS_SLIDESHOWOPTIONS       40162
#define ID_VIEW_ARRANGEICONS            40164
#define ID_VIEW_CUSTOMIZEMAINTOOLBAR    40167
#define ID_VIEW_DESCRIPTION             40168
#define ID_VIEW_EDITACCELERATORS        40169
#define ID_VIEW_FULLSCREEN              40172
#define ID_VIEW_IMAGEEDITBAR            40174
#define ID_VIEW_NORMAL                  40176
#define ID_VIEW_PAUSETHUMBNAILING       40177
#define ID_VIEW_PINIMAGE                40178
#define ID_VIEW_PRINT                   40179
#define ID_VIEW_REFRESHX                40180
#define ID_VIEW_IMAGEFULLSCREEN         40184
#define ID_VIEW_FOLDERS                 40185
#define ID_VIEW_WEB                     40186
#define ID_SLIDESHOW                    40187
#define ID_SLIDESHOW_FULLSCREEN         40200
#define ID_EDIT_DELETE_PERM             40201
#define ID_FOLDERVIEWHEADER_ADDCOLUMN   40202
#define ID_FOLDERVIEWHEADER_REMOVECOLUMN 40203
#define ID_MISC_FOLDERCHANGE            40204
#define ID_DESCTIPTION_IMAGE            40206
#define ID_SLIDESHOW_TOOLBAR            40208
#define ID_FILE_WEBPAGE_REFRESH         40214
#define ID_FILE_WEBPAGE_STOP            40215
#define ID_FILE_MOVETO_POPUP            40227
#define ID_FILE_COPYTO_POPUP            40228
#define ID_APP_TEST                     40231
#define ID_FILTER_CURRENT               40238
#define ID_FILTER_MULTIPLE              40239
#define IDS_OPTION_FADE                 40242
#define IDS_OPTION_BACKBUFFER           40243
#define ID_EDIT_SAVE_MOVENEXT           40247
#define ID_FILE_ZIP                     40248
#define IDS_SENT                        40249
#define IDS_DAYS                        40250
#define IDS_MONTHS                      40251
#define ID_EDIT_UPLOADTOFLICKR          40252
#define ID_THUMBNAILS_THUMBNAIL         40255
#define ID_THUMBNAILS_DETAIL            40256
#define ID_THUMBNAILS_MATRIX            40300
#define ID_THUMBNAILS                   40302
#define ID_ARRANGEICONS_NAME            40303
#define ID_ARRANGEICONS_SIZE            40304
#define ID_ARRANGEICONS_TYPE            40305
#define ID_ARRANGEICONS_MODIFIED        40306
#define ID_ARRANGEICONS_MORE            40307
#define ID_SLIDESHOW_DELAYBETWEENIMAGES_2SECOND 40312
#define ID_VIEW_FLICKR                  40313
#define ID_TOOLS_CONVERTIMAGES          40317
#define ID_TOOLS_TAG                    40318
#define ID_TOOLS_BATCHPROCESS           40320
#define ID_TOOLS_LOSSLESS               40321
#define ID_IMAGE_EDITDESCRIPTION        40324
#define ID_FILE_WEBPAGE_OPTIONS         40325
#define ID_FILE_PRINT_OPTIONS           40327
#define ID_VIEW_ADDRESS                 40330
#define ID_VIEW_SEARCHADVANCED          40331
#define ID_TEST                         40333
#define ID_IMAGE_OPENINFLICKR           40334
#define ID_IMAGE_UPLOADTOFLICKR         40335
#define ID_FILE_OPENCONTAINING          40336
#define IDC_SEARCH_CURRENT              40337
#define ID_SEARCH_MYPICTURES            40339
#define ID_SEARCH_CURRENT               40340
#define ID_SEARCH_STOP                  40341
#define ID_SEARCH_SEARCH                40342
#define ID_SEARCH                       40343
#define ID_TAG                          40344
#define ID_TAG_TAGSELECTEDIMAGES        40345
#define ID_TAG_SELECT                   40347
#define ID_TAG_SELECTED                 40348
#define ID_SEARCH_SEARCHBYDATE          40349
#define ID_SEARCH_DATE                  40350
#define ID_SEARCH_TEXT                  40352
#define ID_TAG_AUTOSELECT               40354
#define ID_EDIT_ROTATELEFT              40357
#define ID_EDIT_ROTATERIGHT             40359
#define IDS_ROTATING                    40361
#define ID_FLICKR_CHANGEUSER            40362
#define IDS_IPTC_FLICKRID               40362
#define ID_FLICKR_CREATEPHOTOSET        40363
#define ID_SCALE_FILL                   40366
#define ID_TAG_REMOVE                   40371
#define ID_FILE_ADDCOPYRIGHT            40375
#define ID_EDIT_SELECTIMAGESONFLICKR    40377
#define ID_ARRANGEICONS_DATETAKEN       40378
#define ID_FLICKR_DOWNLOADIMAGE         40383
#define ID_FILE_OPEN_WITH               40384
#define ID_HELP_REGISTRATIONWEBPAGE     40385
#define ID_FLICKR_NEXT                  40386
#define ID_FLICKR_DOWNLOAD              40388
#define ID_VIEW_ADVANCEDIMAGE           40402
#define ID_SCALE_TOGGLE                 40418
#define ID_SEARCH_IMAGESINSUBFOLDERS    40419
#define ID_OPTIONS_SHOWDESCRIPTIONSINDETAIL 40431
#define ID_OPTIONS_SHOWHIDDENFILES      40432
#define ID_OPTIONS_SHOWMETADATAMARKERS  40433
#define ID_OPTIONS_SHOWTHUMBNAILTOOLTIPS 40434
#define ID_OPTIONS_USESHORTDATES        40435
#define ID_OPTIONS_ZOOMTHUMBNAILSINMATRIXVIEW 40436
#define ID_FILTER_BLUR                  40437
#define ID_FILTER_COLORADJUST           40438
#define ID_FILTER_CONTRASTSTRETCH       40439
#define ID_FILTER_CROP                  40440
#define ID_FILTER_DITHER                40441
#define ID_FILTER_EDGE                  40442
#define ID_FILTER_EMBOS                 40443
#define ID_FILTER_FRAME                 40444
#define ID_FILTER_GRAYSCALE             40445
#define ID_FILTER_NEGATE                40446
#define ID_FILTER_QUANTIZE              40447
#define ID_FILTER_REDEYEREDUCTION       40448
#define ID_FILTER_ROTATE                40451
#define ID_FILTER_ROTATELEFT            40452
#define ID_FILTER_ROTATERIGHT           40453
#define ID_FILTER_SHARPEN               40454
#define ID_FILTER_SOFTEN                40455
#define ID_FILTER_RESIZE                40456
#define ID_TOOLS_RESIZE                 40462
#define ID_SAVE_AS                      40466
#define IDS_OPTION_MMX                  57697
#define IDS_OPTION_HALFTONE             59394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         40469
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
