// ShellExtensions.idl : IDL source for ShellExtensions
//

// This file will be processed by the MIDL tool to
// produce the type library (ShellExtensions.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(DB50584F-9FD5-4050-A022-2A3CBB03DC52),
	dual,
	helpstring("CImageWalker Interface"),
	pointer_default(unique),
	oleautomation

] 
interface IImageWalker : IDispatch
{
	[id(1), helpstring("method OpenFolder")] HRESULT OpenFolder([in] BSTR strFolderName);
	[id(2), helpstring("method ShowFullScreen")] HRESULT ShowFullScreen([in] BSTR strFolderName);
	[id(3), helpstring("method SlideShow")] HRESULT SlideShow([in] BSTR strFolderName);
}; 


[
	object,
	uuid(E8F8428F-7D94-4547-A87B-77DEDCA58D78),
	dual,
	nonextensible,
	helpstring("IFileMenu Interface"),
	pointer_default(unique)
]
interface IFileMenu : IDispatch{
};


[
	object,
	uuid(93DD1DA6-DECB-4A36-9193-53A1F1292665),
	dual,
	nonextensible,
	helpstring("IFolderMenu Interface"),
	pointer_default(unique)
]
interface IFolderMenu : IDispatch{
};


[
	uuid(7A619616-0DC4-4375-9C0F-AB55E2C01C0E),
	version(1.0),
	helpstring("ShellExtensions 1.0 Type Library")
]
library ShellExtensionsLib
{
	importlib("stdole2.tlb");
	[
		uuid(E22C262F-6557-4093-A7D1-52962F6979D0),
		helpstring("ImageWalkerFileMenu Class")
	]
	coclass ImageWalkerFileMenu
	{
		[default] interface IFileMenu;
	};
	[
		uuid(25F0D1D5-EDDE-486A-AB06-B10DF8E19EB0),
		helpstring("ImageWalkerFolderMenu Class")
	]
	coclass ImageWalkerFolderMenu
	{
		[default] interface IFolderMenu;
	};
};
